import 'package:cloud_firestore/cloud_firestore.dart';
import '../../data/models/vehicle_model.dart';

class SeedData {
  static final FirebaseFirestore _firestore = FirebaseFirestore.instance;

  static Future<void> addSampleVehicles(String userId, String userName) async {
    final vehicles = [
      VehicleModel(
        id: '',
        sellerId: userId,
        sellerName: userName,
        brand: 'Renault',
        model: 'Clio 4',
        year: 2019,
        mileage: 45000,
        price: 28000,
        fuelType: FuelType.diesel,
        transmission: TransmissionType.manual,
        engineSize: 1500,
        horsePower: 90,
        color: 'Blanc',
        condition: VehicleCondition.good,
        status: VehicleStatus.available,
        description: 'Renault Clio 4 en excellent état, première main, entretien régulier, jamais accidentée.',
        features: ['Climatisation', 'GPS', 'Bluetooth', 'Régulateur de vitesse'],
        imageUrls: [
          'https://images.unsplash.com/photo-1549399542-7e3f8b79c341?w=800',
        ],
        thumbnailUrl: 'https://images.unsplash.com/photo-1549399542-7e3f8b79c341?w=400',
        city: 'Tunis',
        address: 'Centre ville',
        numberOfOwners: 1,
        hasAccidents: false,
        createdAt: DateTime.now().subtract(const Duration(days: 2)),
        updatedAt: DateTime.now(),
      ),
      VehicleModel(
        id: '',
        sellerId: userId,
        sellerName: userName,
        brand: 'Peugeot',
        model: '208',
        year: 2020,
        mileage: 32000,
        price: 32000,
        fuelType: FuelType.gasoline,
        transmission: TransmissionType.automatic,
        engineSize: 1200,
        horsePower: 82,
        color: 'Gris',
        condition: VehicleCondition.excellent,
        status: VehicleStatus.available,
        description: 'Peugeot 208 automatique, très économique, idéale pour la ville.',
        features: ['Climatisation', 'Caméra de recul', 'Bluetooth', 'Airbags'],
        imageUrls: [
          'https://images.unsplash.com/photo-1552519507-da3b142c6e3d?w=800',
        ],
        thumbnailUrl: 'https://images.unsplash.com/photo-1552519507-da3b142c6e3d?w=400',
        city: 'Sousse',
        numberOfOwners: 1,
        hasAccidents: false,
        createdAt: DateTime.now().subtract(const Duration(days: 5)),
        updatedAt: DateTime.now(),
      ),
      VehicleModel(
        id: '',
        sellerId: userId,
        sellerName: userName,
        brand: 'Volkswagen',
        model: 'Golf 7',
        year: 2018,
        mileage: 68000,
        price: 42000,
        fuelType: FuelType.diesel,
        transmission: TransmissionType.manual,
        engineSize: 2000,
        horsePower: 150,
        color: 'Noir',
        condition: VehicleCondition.good,
        status: VehicleStatus.available,
        description: 'VW Golf 7 GTD, très performante, bien entretenue.',
        features: ['GPS', 'Toit ouvrant', 'Sièges en cuir', 'Phares LED'],
        imageUrls: [
          'https://images.unsplash.com/photo-1617469767053-d3b523a0b982?w=800',
        ],
        thumbnailUrl: 'https://images.unsplash.com/photo-1617469767053-d3b523a0b982?w=400',
        city: 'Sfax',
        numberOfOwners: 2,
        hasAccidents: false,
        createdAt: DateTime.now().subtract(const Duration(days: 1)),
        updatedAt: DateTime.now(),
      ),
      VehicleModel(
        id: '',
        sellerId: userId,
        sellerName: userName,
        brand: 'Toyota',
        model: 'Corolla',
        year: 2021,
        mileage: 25000,
        price: 55000,
        fuelType: FuelType.hybrid,
        transmission: TransmissionType.automatic,
        engineSize: 1800,
        horsePower: 122,
        color: 'Bleu',
        condition: VehicleCondition.excellent,
        status: VehicleStatus.available,
        description: 'Toyota Corolla Hybride, très économique, garantie constructeur.',
        features: ['Climatisation', 'Caméra de recul', 'GPS', 'Sièges chauffants', 'Système audio premium'],
        imageUrls: [
          'https://images.unsplash.com/photo-1621007947382-bb3c3994e3fb?w=800',
        ],
        thumbnailUrl: 'https://images.unsplash.com/photo-1621007947382-bb3c3994e3fb?w=400',
        city: 'Ariana',
        numberOfOwners: 1,
        hasAccidents: false,
        createdAt: DateTime.now().subtract(const Duration(hours: 12)),
        updatedAt: DateTime.now(),
      ),
      VehicleModel(
        id: '',
        sellerId: userId,
        sellerName: userName,
        brand: 'Hyundai',
        model: 'Tucson',
        year: 2019,
        mileage: 52000,
        price: 48000,
        fuelType: FuelType.diesel,
        transmission: TransmissionType.automatic,
        engineSize: 1600,
        horsePower: 136,
        color: 'Rouge',
        condition: VehicleCondition.good,
        status: VehicleStatus.available,
        description: 'SUV spacieux et confortable, parfait pour les familles.',
        features: ['Climatisation', 'GPS', 'Caméra de recul', 'Toit panoramique', 'Capteurs de stationnement'],
        imageUrls: [
          'https://images.unsplash.com/photo-1519641471654-76ce0107ad1b?w=800',
        ],
        thumbnailUrl: 'https://images.unsplash.com/photo-1519641471654-76ce0107ad1b?w=400',
        city: 'Nabeul',
        numberOfOwners: 1,
        hasAccidents: false,
        createdAt: DateTime.now().subtract(const Duration(days: 3)),
        updatedAt: DateTime.now(),
      ),
    ];

    for (final vehicle in vehicles) {
      final docRef = await _firestore.collection('vehicles').add(vehicle.toMap());
      await docRef.update({'id': docRef.id});
    }
  }
}