// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAC_Hq7Z_3vCEJVFwGVSV9zXNYvi2Jg3V0',
    appId: '1:994315803304:web:8e9cc667643e8cc596c09d',
    messagingSenderId: '994315803304',
    projectId: 'occazcar-project',
    authDomain: 'occazcar-project.firebaseapp.com',
    storageBucket: 'occazcar-project.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDl0aRtWEjwCJAjVugfszxIMgR5OXmvSe8',
    appId: '1:994315803304:android:f76985f5b9c9db7596c09d',
    messagingSenderId: '994315803304',
    projectId: 'occazcar-project',
    storageBucket: 'occazcar-project.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGQ_MDBQuQkD6xtqrE3sj5E1xUkoZnoy4',
    appId: '1:994315803304:ios:44b03393ef9e3cb796c09d',
    messagingSenderId: '994315803304',
    projectId: 'occazcar-project',
    storageBucket: 'occazcar-project.firebasestorage.app',
    iosBundleId: 'com.example.occazcar',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDGQ_MDBQuQkD6xtqrE3sj5E1xUkoZnoy4',
    appId: '1:994315803304:ios:44b03393ef9e3cb796c09d',
    messagingSenderId: '994315803304',
    projectId: 'occazcar-project',
    storageBucket: 'occazcar-project.firebasestorage.app',
    iosBundleId: 'com.example.occazcar',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAC_Hq7Z_3vCEJVFwGVSV9zXNYvi2Jg3V0',
    appId: '1:994315803304:web:8e9cc667643e8cc596c09d',
    messagingSenderId: '994315803304',
    projectId: 'occazcar-project',
    authDomain: 'occazcar-project.firebaseapp.com',
    storageBucket: 'occazcar-project.firebasestorage.app',
  );
}
